Repository comit-network/comit-rs, pull requests merged in 2018-12, with the labels that each got.

#564 Fix typos
  .github/ISSUE_TEMPLATE/feature-request.md
  Makefile.toml
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_contract.asm
Labels: review

#556 More Rust 2018 Idioms
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/http_api/problem.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/item_cache.rs
  application/comit_node/src/ledger_query_service/bitcoin.rs
  application/comit_node/src/ledger_query_service/cache.rs
  application/comit_node/src/ledger_query_service/client.rs
  application/comit_node/src/ledger_query_service/ethereum.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/logging.rs
  application/comit_node/src/seed.rs
  application/comit_node/src/swap_protocols/rfc003/actions/bob/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/extract_secret.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/bob/swap_response.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/extract_secret.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs
  application/comit_node/src/swap_protocols/rfc003/secret.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  application/comit_node/tests/ethereum_wallet/transaction.rs
  application/comit_node/tests/htlc_harness/erc20_harness.rs
  application/comit_node/tests/htlc_harness/ether_harness.rs
  application/comit_node/tests/parity_client/parity_client.rs
  application/comit_node/tests/rfc003_erc20_htlc.rs
  application/comit_node/tests/rfc003_ether_htlc.rs
  application/comit_node_client/src/api_client/client.rs
  application/comit_node_client/src/api_client/mod.rs
  application/comit_node_client/src/bin/comit_node_client.rs
  application/comit_node_client/src/lib.rs
  application/ledger_query_service/src/bin/ledger_query_service.rs
  application/ledger_query_service/src/ledgers/bitcoin.rs
  application/ledger_query_service/src/ledgers/ethereum.rs
  application/ledger_query_service/src/lib.rs
  application/ledger_query_service/src/route_factory.rs
  application/ledger_query_service/src/routes.rs
  application/ledger_query_service/src/settings/mod.rs
  vendor/bam/src/client.rs
  vendor/bam/src/lib.rs
  vendor/bitcoin_rpc_test_helpers/src/lib.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/bitcoin_support/src/transaction.rs
  vendor/bitcoin_witness/src/lib.rs
  vendor/ethereum_support/src/contract_address.rs
  vendor/ethereum_support/src/key.rs
  vendor/ethereum_support/src/lib.rs
  vendor/ethereum_support/tests/ether_quantity.rs
  vendor/secp256k1_support/src/keypair.rs
  vendor/secp256k1_support/src/lib.rs
  vendor/secp256k1_support/src/public_key.rs
  vendor/tc_bitcoincore_client/src/lib.rs
  vendor/tc_web3_client/src/lib.rs
Labels: review

#558 Move BTC setup to JS
  api_tests/dry/harness.sh
  api_tests/e2e/comit-harness.sh
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/harness-lib.sh
  api_tests/ledger_query_service/harness.sh
  api_tests/ledger_query_service/test.js
  api_tests/test_lib.js
Labels: review

#570 Remove outdated COMIT node client
  Cargo.lock
  Cargo.toml
  application/comit_node_client/Cargo.toml
  application/comit_node_client/src/api_client/client.rs
  application/comit_node_client/src/api_client/mod.rs
  application/comit_node_client/src/bin/comit_node_client.rs
  application/comit_node_client/src/lib.rs
Labels: added-mid-sprint, review

#574 Add mergify configuration
  .mergify.yml
Labels: review

#571 Use config file for test dependencies
  .gitignore
  Makefile.toml
  api_tests/dry/harness.sh
  api_tests/dry/rfc003/config.toml
  api_tests/dry/rfc003/test.js
  api_tests/e2e/comit-harness.sh
  api_tests/e2e/rfc003/btc_eth-erc20/config.toml
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/config.toml
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/harness-lib.sh
  api_tests/harness.js
  api_tests/ledger_query_service/config.toml
  api_tests/ledger_query_service/harness.sh
  api_tests/ledger_query_service/test.js
  api_tests/npm_wrapper.sh
  api_tests/package.json
  api_tests/regtest/alice/erc20.toml
  api_tests/regtest/bob/erc20.toml
  api_tests/regtest/ledgers.toml
  api_tests/regtest/regtest.env
  api_tests/test_lib.js
  application/comit_node/src/logging.rs
Labels: review

#580 Remove rustic_hal fork dependency
  Cargo.lock
  Cargo.toml
  application/comit_node/Cargo.toml
Labels: review

#582 [fix mergify] Rename status check as per our Travis setup
  .mergify.yml
Labels: added-mid-sprint

#567 Clarify installation of cargo subcommands
  README.md
Labels: added-mid-sprint, review

#581 Test should not be controlling bitcoin blocks gen
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/harness.js
  api_tests/test_lib.js
  application/comit_node/src/http_api/rfc003/swap.rs
Labels: review

#572 Bob can decline a swap request
  api_tests/dry/rfc003/test.js
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/swap_protocols/rfc003/actions/bob/mod.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  vendor/bam/src/json/response.rs
Labels: review

#588 Revert "Bob can decline a swap request"
  api_tests/dry/rfc003/test.js
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/swap_protocols/rfc003/actions/bob/mod.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  vendor/bam/src/json/response.rs
Labels: review

#594 Implement PR suggestions in a different PR because you forget to push changes before merging
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/swap_protocols/metadata_store.rs
Labels: review

#587 Use futures in LQS
  Cargo.lock
  application/ledger_query_service/Cargo.toml
  application/ledger_query_service/src/bin/ledger_query_service.rs
  application/ledger_query_service/src/bitcoind_zmq_listener.rs
  application/ledger_query_service/src/block_processor.rs
  application/ledger_query_service/src/connectors/bitcoind_zmq_listener.rs
  application/ledger_query_service/src/connectors/ethereum_web3_block_poller.rs
  application/ledger_query_service/src/connectors/mod.rs
  application/ledger_query_service/src/ethereum_web3_block_poller.rs
  application/ledger_query_service/src/lib.rs
  application/ledger_query_service/src/queries/bitcoin.rs
  application/ledger_query_service/src/queries/ethereum.rs
  application/ledger_query_service/src/queries/mod.rs
  vendor/bitcoin_support/src/mined_block.rs
Labels: review

#586 Check Secret Length in Bitcoin HTLC
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs
  application/comit_node/src/swap_protocols/rfc003/mod.rs
  application/comit_node/src/swap_protocols/rfc003/secret.rs
  application/comit_node/tests/rfc003_bitcoin_htlc.rs
Labels: review

#602 Bob can decline post mortem
  vendor/bam/src/json/frame.rs
  vendor/bam/src/json/response.rs
Labels: review

#597 Missing feedback from last PR
  application/ledger_query_service/src/block_processor.rs
Labels: review

#607 Add instructions to install zeromq
  README.md
Labels: review

#573 Replace "handlers" with generic "spawners"
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/comit_server.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/rfc003/with_swap_types.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/swap_protocols/dependencies.rs
  application/comit_node/src/swap_protocols/mod.rs
  application/comit_node/src/swap_protocols/rfc003/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/communication_events.rs
  application/comit_node/src/swap_protocols/rfc003/alice/handler.rs
  application/comit_node/src/swap_protocols/rfc003/alice/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/alice/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/communication_events.rs
  application/comit_node/src/swap_protocols/rfc003/bob/handler.rs
  application/comit_node/src/swap_protocols/rfc003/bob/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/bob/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/bob/swap_response.rs
  application/comit_node/src/swap_protocols/rfc003/create_ledger_events.rs
  application/comit_node/src/swap_protocols/rfc003/events/mod.rs
  application/comit_node/src/swap_protocols/rfc003/mod.rs
  application/comit_node/src/swap_protocols/rfc003/role.rs
  application/comit_node/src/swap_protocols/rfc003/roles.rs
  application/comit_node/src/swap_protocols/rfc003/save_state.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine_test.rs
  application/comit_node/src/swap_protocols/rfc003/state_store.rs
Labels: review
