Repository comit-network/comit-rs, pull requests merged in 2019-08, with the labels that each got.

#1135 Don't consider overfunded/underfunded HTLCs as funded
  api_tests/e2e/rfc003/btc_eth/overfunded_htlc.ts
  api_tests/e2e/rfc003/btc_eth/underfunded_htlc.ts
  api_tests/lib/test_creator.ts
  cnd/src/http_api/routes/rfc003/swap_state.rs
  cnd/src/swap_protocols/asset.rs
  cnd/src/swap_protocols/rfc003/actions/bitcoin.rs
  cnd/src/swap_protocols/rfc003/actions/ether.rs
  cnd/src/swap_protocols/rfc003/actions/mod.rs
  cnd/src/swap_protocols/rfc003/alice/actions/erc20.rs
  cnd/src/swap_protocols/rfc003/alice/actions/generic_impl.rs
  cnd/src/swap_protocols/rfc003/bob/actions/erc20.rs
  cnd/src/swap_protocols/rfc003/bob/actions/generic_impl.rs
  cnd/src/swap_protocols/rfc003/error.rs
  cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs
  cnd/src/swap_protocols/rfc003/ledger_state.rs
  cnd/src/swap_protocols/rfc003/state_machine.rs
  cnd/src/swap_protocols/rfc003/state_store.rs
Labels: automagically-mergify-this

#1154 Libp2p refactor substream code
  cnd/src/libp2p_bam/behaviour.rs
  cnd/src/libp2p_bam/handler.rs
  cnd/src/libp2p_bam/mod.rs
  cnd/src/libp2p_bam/substream/inbound.rs
  cnd/src/libp2p_bam/substream/mod.rs
  cnd/src/libp2p_bam/substream/outbound.rs
  cnd/src/network.rs
  cnd/src/swap_protocols/dependencies/client_impl.rs
  vendor/bam/src/json/request.rs
Labels: automagically-mergify-this

#1168 Remove chai big number
  api_tests/package.json
  api_tests/yarn.lock
Labels: added-mid-sprint, automagically-mergify-this

#1169 Detect missing block for bitcoin
  btsieve/src/bitcoin/mod.rs
  btsieve/src/lib.rs
  btsieve/src/main.rs
  vendor/bitcoin_support/src/mined_block.rs
Labels: automagically-mergify-this

#1159 Allow users to configure structured logging which outputs all log messages in JSON format
  Cargo.lock
  cnd/Cargo.toml
  cnd/src/config/file.rs
  cnd/src/config/mod.rs
  cnd/src/config/settings.rs
  cnd/src/logging.rs
  cnd/src/logging/initialize.rs
  cnd/src/logging/mod.rs
  cnd/src/main.rs
  cnd/tests/config.rs
Labels: automagically-mergify-this

#1171 libp2p_bam: Add comments on enum variants
  cnd/src/libp2p_bam/substream/inbound.rs
  cnd/src/libp2p_bam/substream/outbound.rs
Labels: added-mid-sprint

#1175 Move `ComitRunner` into its own file and name it `CndRunner`
  api_tests/harness.ts
  api_tests/lib/cnd_runner.ts
Labels: added-mid-sprint, automagically-mergify-this

#1176 Minor simplifications to the recently added tests for implementation of the `Blockchain`-trait for Ethereum
  btsieve/src/ethereum/mod.rs
Labels: added-mid-sprint, automagically-mergify-this

#1196 Replace configuration option for poll interval with sophisticated algorithm
  api_tests/regtest/btsieve/btsieve.toml
  api_tests/regtest/btsieve/ethereum_only/btsieve.toml
  btsieve/config/btsieve.toml
  btsieve/config/ethereum_only.toml
  btsieve/src/main.rs
  btsieve/src/settings/mod.rs
  btsieve/src/settings/serde_duration.rs
Labels: added-mid-sprint, automagically-mergify-this

#1189 Add test-harness for testing substream state transitions
  Cargo.lock
  cnd/Cargo.toml
  cnd/src/libp2p_bam/handler.rs
  cnd/src/libp2p_bam/mod.rs
  cnd/src/libp2p_bam/substream/inbound.rs
  cnd/src/libp2p_bam/substream/outbound.rs
  cnd/src/libp2p_bam/test_harness.rs
  vendor/bam/src/json/header.rs
  vendor/bam/src/json/response.rs
Labels: added-mid-sprint, automagically-mergify-this

#1193 Properly use cargo make to allow auto install of rustfmt
  Makefile.toml
Labels: added-mid-sprint, automagically-mergify-this

#1201 Remove ethereum_support dependency from blockchain_contracts
  Cargo.lock
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/mod.rs
  vendor/blockchain_contracts/src/ethereum/mod.rs
  vendor/blockchain_contracts/src/ethereum/to_ethereum_address.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/transaction.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/wallet.rs
  vendor/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/ether_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/mod.rs
  vendor/blockchain_contracts/tests/parity_client/parity_client.rs
  vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
Labels: automagically-mergify-this

#1197 Remove bitcoin_support dependency from blockchain_contracts
  Cargo.lock
  cnd/src/swap_protocols/rfc003/bitcoin/mod.rs
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/src/bitcoin/mod.rs
  vendor/blockchain_contracts/src/bitcoin/pubkey_hash.rs
  vendor/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs
  vendor/blockchain_contracts/src/fit_into_placeholder_slice.rs
  vendor/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
  vendor/secp256k1_support/src/keypair.rs
Labels: automagically-mergify-this

#1207 Make use of predefined check-format task
  Makefile.toml
Labels: added-mid-sprint

#1198 Indicate file location in README
  README.md
Labels: added-mid-sprint, automagically-mergify-this

#1208 Bump comit-i version
  vendor/comit_i/version
Labels: automagically-mergify-this

#1204 Strip secp256k1_support crate
  Cargo.lock
  btsieve/Cargo.toml
  cnd/Cargo.toml
  cnd/src/swap_protocols/ledger/bitcoin.rs
  cnd/src/swap_protocols/ledger/ethereum.rs
  cnd/src/swap_protocols/rfc003/secret_source.rs
  cnd/src/swap_protocols/rfc003/state_store.rs
  vendor/bitcoin_support/Cargo.toml
  vendor/bitcoin_support/src/pubkey.rs
  vendor/bitcoin_witness/Cargo.toml
  vendor/bitcoin_witness/src/p2wpkh.rs
  vendor/bitcoin_witness/src/primed_transaction.rs
  vendor/bitcoin_witness/src/witness.rs
  vendor/bitcoin_witness/tests/p2wpkh.rs
  vendor/bitcoin_witness/tests/sign_with_rate.rs
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/src/bitcoin/pubkey_hash.rs
  vendor/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs
  vendor/blockchain_contracts/src/ethereum/to_ethereum_address.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/wallet.rs
  vendor/blockchain_contracts/tests/htlc_harness/mod.rs
  vendor/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
  vendor/ethereum_support/Cargo.toml
  vendor/ethereum_support/src/key.rs
  vendor/key_gen/Cargo.toml
  vendor/key_gen/src/main.rs
  vendor/secp256k1_keypair/Cargo.toml
  vendor/secp256k1_keypair/src/keypair.rs
  vendor/secp256k1_keypair/src/lib.rs
  vendor/secp256k1_support/src/public_key.rs
Labels: automagically-mergify-this

#1216 Move bitcoin_quantity to dev dep
  internal/blockchain_contracts/Cargo.toml
Labels: automagically-mergify-this

#1217 Remove test related deps from blockchain_contracts
  Cargo.lock
  internal/blockchain_contracts/Cargo.toml
  internal/blockchain_contracts/tests/bitcoin_helper/mod.rs
  internal/blockchain_contracts/tests/ethereum_helper/mod.rs
  internal/blockchain_contracts/tests/ethereum_helper/tc_web3_client.rs
  internal/blockchain_contracts/tests/ethereum_helper/transaction.rs
  internal/blockchain_contracts/tests/ethereum_helper/wallet.rs
  internal/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  internal/blockchain_contracts/tests/htlc_harness/ether_harness.rs
  internal/blockchain_contracts/tests/parity_client/parity_client.rs
  internal/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
  internal/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  internal/blockchain_contracts/tests/rfc003_ether_htlc.rs
Labels: automagically-mergify-this

#1215 Activate clippy for test code, fix warnings
  Makefile.toml
  btsieve/src/bitcoin/mod.rs
  btsieve/src/bitcoin/queries/transaction.rs
  btsieve/src/ethereum/queries/event.rs
  cnd/src/http_api/mod.rs
  cnd/src/http_api/routes/rfc003/handlers/post_swap.rs
  cnd/src/libp2p_bam/handler.rs
  cnd/src/logging/initialize.rs
  cnd/src/swap_protocols/rfc003/state_store.rs
  internal/bitcoin_support/src/network.rs
  internal/bitcoin_support/src/pubkey.rs
  internal/bitcoin_witness/src/p2wpkh.rs
  internal/bitcoin_witness/src/primed_transaction.rs
  internal/bitcoin_witness/tests/p2wpkh.rs
  internal/bitcoin_witness/tests/sign_with_rate.rs
  internal/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs
  internal/blockchain_contracts/src/ethereum/rfc003/erc20_htlc.rs
  internal/blockchain_contracts/src/ethereum/rfc003/ether_htlc.rs
  internal/blockchain_contracts/tests/ethereum_helper/wallet.rs
  internal/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  internal/blockchain_contracts/tests/htlc_harness/ether_harness.rs
  internal/blockchain_contracts/tests/htlc_harness/timestamp.rs
  internal/blockchain_contracts/tests/parity_client/mod.rs
  internal/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
  internal/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  internal/blockchain_contracts/tests/rfc003_ether_htlc.rs
  internal/ethereum_support/src/network.rs
Labels: automagically-mergify-this

#1213 Remove secp256k1_keypair dep from blockchain_contracts
  Cargo.lock
  cnd/src/swap_protocols/rfc003/actions/bitcoin.rs
  internal/bitcoin_witness/src/p2wpkh.rs
  internal/bitcoin_witness/src/primed_transaction.rs
  internal/bitcoin_witness/src/witness.rs
  internal/blockchain_contracts/Cargo.toml
  internal/blockchain_contracts/src/bitcoin/rfc003/bitcoin_htlc.rs
  internal/blockchain_contracts/src/ethereum/to_ethereum_address.rs
  internal/blockchain_contracts/src/lib.rs
  internal/blockchain_contracts/tests/ethereum_helper/wallet.rs
  internal/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  internal/blockchain_contracts/tests/htlc_harness/mod.rs
  internal/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
Labels: automagically-mergify-this

#1202 Don't rebase to update a branch
  .mergify.yml
Labels: added-mid-sprint

#1192 Introduce `BlockSource` and implement it for `Web3<Http>`
  btsieve/src/blocksource.rs
  btsieve/src/ethereum/ethereum_web3_block_poller.rs
  btsieve/src/ethereum/mod.rs
  btsieve/src/ethereum/web3_http_blocksource.rs
  btsieve/src/lib.rs
  btsieve/src/main.rs
  btsieve/tests/web3_http_blocksource.rs
Labels: automagically-mergify-this

#1241 Remove blockheight queries
  api_tests/btsieve/bitcoin_only/test.ts
  api_tests/btsieve/ethereum_only/test.ts
  btsieve/src/bitcoin/block_processor.rs
  btsieve/src/bitcoin/mod.rs
  btsieve/src/bitcoin/queries/block.rs
  btsieve/src/bitcoin/queries/mod.rs
  btsieve/src/ethereum/block_processor.rs
  btsieve/src/ethereum/mod.rs
  btsieve/src/ethereum/queries/block.rs
  btsieve/src/ethereum/queries/mod.rs
  btsieve/src/main.rs
  cnd/src/btsieve/bitcoin.rs
  cnd/src/btsieve/client.rs
  cnd/src/btsieve/ethereum.rs
Labels: added-mid-sprint, automagically-mergify-this, 🥰 feels-good

#1223 Refresh contributing and mention changelog
  CONTRIBUTING.md
Labels: added-mid-sprint, automagically-mergify-this

#1240 Upgrade web3 to 0.8
  Cargo.lock
  btsieve/Cargo.toml
  btsieve/src/ethereum/mod.rs
  btsieve/src/ethereum/queries/event.rs
  btsieve/src/ethereum/queries/transaction.rs
  btsieve/src/ethereum/web3_http_blocksource.rs
  cnd/Cargo.toml
  cnd/src/btsieve/ethereum.rs
  cnd/src/http_api/mod.rs
  cnd/src/http_api/routes/rfc003/handlers/post_swap.rs
  cnd/src/swap_protocols/asset.rs
  cnd/src/swap_protocols/rfc003/ethereum/htlc_events.rs
  internal/blockchain_contracts/Cargo.toml
  internal/blockchain_contracts/src/ethereum/to_ethereum_address.rs
  internal/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  internal/blockchain_contracts/tests/rfc003_ether_htlc.rs
  internal/ethereum_support/Cargo.toml
  internal/ethereum_support/src/contract_address.rs
  internal/ethereum_support/src/key.rs
  internal/ethereum_support/src/lib.rs
  internal/tc_web3_client/Cargo.toml
Labels: added-mid-sprint, automagically-mergify-this

#1242 Use cross platform config directory (cnd)
  CHANGELOG.md
  cnd/src/config/file.rs
  cnd/src/main.rs
  cnd/tests/config.rs
Labels: added-mid-sprint, automagically-mergify-this

#1233 Upgrade libp2p to v0.12
  Cargo.lock
  btsieve/Cargo.toml
  cnd/Cargo.toml
  cnd/src/libp2p_bam/behaviour.rs
  cnd/src/libp2p_bam/handler.rs
  cnd/src/libp2p_bam/mod.rs
  cnd/src/libp2p_bam/substream/inbound.rs
  cnd/src/libp2p_bam/substream/mod.rs
  cnd/src/libp2p_bam/substream/outbound.rs
  cnd/src/libp2p_bam/test_harness.rs
  cnd/src/network.rs
Labels: added-mid-sprint, automagically-mergify-this

#1251 Fix CHANGELOG.md
  CHANGELOG.md
Labels: added-mid-sprint, automagically-mergify-this

#1261 Fix yarn commands in README.md
  README.md
Labels: automagically-mergify-this

#1286 Fix lockfile
  api_tests/yarn.lock
Labels: added-mid-sprint
