Repository comit-network/comit-rs, pull requests merged in 2019-03, with the labels that each got.

#803 Make sure we always run against node 11.10
  .travis.yml
  Makefile.toml
  README.md
  api_tests/npm_wrapper.sh
  api_tests/package.json
Labels: review

#801 Update rustic_hal to version 0.2
  Cargo.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
  application/comit_node/src/http_api/rfc003/routes.rs
Labels: review

#806 Use Network::Mainnet instead of Network::Bitcoin
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_support/src/network.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/key_gen/src/main.rs
Labels: automagically-mergify-this, review

#805 Don't restart nodes between tests
  .travis.yml
  Makefile.toml
  api_tests/dry/multiple_peers.js
  api_tests/dry/rfc003_swap_reject.js
  api_tests/dry/sanity.js
  api_tests/dry/stateless.js
  api_tests/e2e/rfc003/btc_eth-erc20/happy.js
  api_tests/e2e/rfc003/btc_eth/happy.js
  api_tests/e2e/rfc003/eth-erc20_btc/happy.js
  api_tests/e2e/rfc003/eth_btc/happy.js
  api_tests/harness.js
  api_tests/lib/actor.js
  api_tests/npm_wrapper.sh
  api_tests/package.json
  api_tests/regtest/ledgers.toml
  api_tests/yarn.lock
Labels: automagically-mergify-this

#807 Convert bitcoin.js and ethereum.js to TypeScript
  .gitignore
  Makefile.toml
  api_tests/.prettierignore
  api_tests/btsieve/test.js
  api_tests/dry/multiple_peers.js
  api_tests/dry/rfc003_swap_reject.js
  api_tests/e2e/rfc003/btc_eth-erc20/happy.js
  api_tests/e2e/rfc003/btc_eth/happy.js
  api_tests/e2e/rfc003/eth-erc20_btc/happy.js
  api_tests/e2e/rfc003/eth_btc/happy.js
  api_tests/harness.js
  api_tests/lib/actor.js
  api_tests/lib/bitcoin.js
  api_tests/lib/bitcoin.ts
  api_tests/lib/ethereum.js
  api_tests/lib/ethereum.ts
  api_tests/lib/wallet.js
  api_tests/lib/wallet.ts
  api_tests/package.json
  api_tests/regtest/ledgers.toml
  api_tests/tsconfig.json
  api_tests/yarn.lock
Labels: review

#814 Revise HTTP API module structure
  api_tests/dry/rfc003_swap_reject.js
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/problem.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
  application/comit_node/src/http_api/rfc003/mod.rs
  application/comit_node/src/http_api/rfc003/socket_addr.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/http_api/routes/index/handlers/get_swaps.rs
  application/comit_node/src/http_api/routes/index/handlers/mod.rs
  application/comit_node/src/http_api/routes/index/mod.rs
  application/comit_node/src/http_api/routes/mod.rs
  application/comit_node/src/http_api/routes/peers/mod.rs
  application/comit_node/src/http_api/routes/rfc003/action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/mod.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/post_action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs
  application/comit_node/src/http_api/routes/rfc003/mod.rs
  application/comit_node/src/http_api/routes/rfc003/swap_state.rs
  application/comit_node/src/http_api/serde.rs
  application/comit_node/src/http_api/swap_resource.rs
  application/comit_node/src/http_api/with_swap_types.rs
  application/comit_node/src/http_api/with_swap_types_bob.rs
Labels: review

#809 Add CORS headers to comit_node HTTP API
  api_tests/dry/sanity.js
  application/comit_node/src/http_api/route_factory.rs
Labels: automagically-mergify-this, review

#817 Add btsieve support for ledger networks
  Cargo.lock
  api_tests/btsieve/test.js
  api_tests/regtest/alice/default.toml
  api_tests/regtest/bob/default.toml
  api_tests/regtest/btsieve/default.toml
  api_tests/regtest/charlie/default.toml
  application/btsieve/config/default.toml
  application/btsieve/src/bin/btsieve.rs
  application/btsieve/src/route_factory.rs
  application/btsieve/src/routes.rs
  application/btsieve/src/settings/mod.rs
  application/comit_node/config/default.toml
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/btsieve/client.rs
  application/comit_node/src/settings/mod.rs
  vendor/bitcoin_support/Cargo.toml
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_support/src/network.rs
  vendor/ethereum_support/Cargo.toml
  vendor/ethereum_support/src/lib.rs
  vendor/ethereum_support/src/network.rs
Labels: review

#820 Resolve two TODOs that continued to pop up
  Cargo.lock
  application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
Labels: review

#819 Consolidate e2e tests
  .gitignore
  .idea/misc.xml
  Makefile.toml
  api_tests/btsieve/test.ts
  api_tests/dry/multiple_peers.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/test_creator.ts
  api_tests/harness.ts
  api_tests/lib/actor.ts
  api_tests/lib/btsieve.ts
  api_tests/lib/comit.ts
  api_tests/lib/ethereum.ts
  api_tests/lib/util.ts
  api_tests/package.json
  api_tests/yarn.lock
Labels: automagically-mergify-this, review

#821 Allow preflight requests with OPTIONS method
  api_tests/dry/multiple_peers.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  application/comit_node/src/http_api/asset.rs
  application/comit_node/src/http_api/impl_serialize_http.rs
  application/comit_node/src/http_api/ledger.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
Labels: automagically-mergify-this, review

#834 Fix loading settings in btsieve
  Cargo.lock
  application/btsieve/Cargo.toml
  application/btsieve/src/bin/btsieve.rs
Labels: review
