Repository comit-network/comit-rs, pull requests merged in 2019-05, with the labels that each got.

#901 Fix Makefile
  Makefile.toml
Labels: automagically-mergify-this, review

#887 New blockchain_contracts crate
  .idea/swap.iml
  Cargo.lock
  Cargo.toml
  application/comit_node/src/swap_protocols/rfc003/mod.rs
  application/comit_node/src/swap_protocols/rfc003/secret.rs
  application/comit_node/tests/mocks/mocks.rs
  application/comit_node/tests/mocks/mod.rs
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/README.md
  vendor/blockchain_contracts/build.rs
  vendor/blockchain_contracts/src/bin/print_offsets.rs
  vendor/blockchain_contracts/src/ethereum/mod.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/erc20_htlc.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/ether_htlc.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/mod.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/templates/.gitignore
  vendor/blockchain_contracts/src/ethereum/rfc003/templates/deploy_header.asm
  vendor/blockchain_contracts/src/ethereum/rfc003/templates/erc20_contract.asm
  vendor/blockchain_contracts/src/ethereum/rfc003/templates/ether_contract.asm
  vendor/blockchain_contracts/src/lib.rs
  vendor/blockchain_contracts/src/rfc003/mod.rs
  vendor/blockchain_contracts/src/rfc003/seconds.rs
  vendor/blockchain_contracts/src/rfc003/secret.rs
  vendor/blockchain_contracts/src/rfc003/secret_hash.rs
  vendor/blockchain_contracts/src/rfc003/timestamp.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/mod.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/transaction.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/wallet.rs
  vendor/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/ether_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/mod.rs
  vendor/blockchain_contracts/tests/parity_client/erc20_token_contract.asm.hex
  vendor/blockchain_contracts/tests/parity_client/mod.rs
  vendor/blockchain_contracts/tests/parity_client/parity_client.rs
  vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
Labels: automagically-mergify-this, review

#898 Refactor actions to embed validity information
  api_tests/btsieve/bitcoin_only/test.ts
  api_tests/btsieve/ethereum_only/test.ts
  api_tests/btsieve/no_ledger/test.ts
  api_tests/dry/multiple_peers.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/btc_eth/refund.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/refund.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/refund_beta.ts
  api_tests/e2e/test_creator.ts
  api_tests/harness.ts
  api_tests/lib/actor.ts
  api_tests/lib/bitcoin.ts
  api_tests/lib/btsieve.ts
  api_tests/lib/btsieve_runner.ts
  api_tests/lib/comit.ts
  api_tests/lib/ethereum.ts
  api_tests/lib/ledger_runner.ts
  api_tests/lib/util.ts
  api_tests/lib/wallet.ts
  api_tests/tsconfig.json
  api_tests/webgui/webgui.ts
  application/comit_node/src/http_api/routes/rfc003/action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/post_action.rs
  application/comit_node/src/swap_protocols/rfc003/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/actions/ether.rs
  application/comit_node/src/swap_protocols/rfc003/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/generic_impl.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/generic_impl.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/actions.rs
  application/comit_node/src/swap_protocols/rfc003/mod.rs
Labels: automagically-mergify-this, review

#918 Remove incorrect data from payload
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
Labels: automagically-mergify-this, review

#921 Strum & nightly upgrade
  Cargo.lock
  rust-toolchain
  vendor/bitcoin_support/Cargo.toml
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/src/lib.rs
  vendor/ethereum_support/Cargo.toml
Labels: automagically-mergify-this

#878 Move network communication to libp2p
  Cargo.lock
  api_tests/dry/multiple_peers.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/btc_eth/refund.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/refund.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/refund_beta.ts
  api_tests/harness.ts
  api_tests/lib/actor.ts
  api_tests/package.json
  api_tests/regtest/alice/default.toml
  api_tests/regtest/bob/default.toml
  api_tests/regtest/charlie/default.toml
  api_tests/regtest/david/default.toml
  api_tests/yarn.lock
  application/comit_node/Cargo.toml
  application/comit_node/config/default.toml
  application/comit_node/src/bam_api/mod.rs
  application/comit_node/src/bam_api/rfc003/mod.rs
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_server.rs
  application/comit_node/src/connection_pool.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/http_api/routes/index/mod.rs
  application/comit_node/src/http_api/routes/peers/mod.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/post_swap.rs
  application/comit_node/src/http_api/serde_peer_id.rs
  application/comit_node/src/http_api/serde_socket_addr.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/libp2p_bam/behaviour.rs
  application/comit_node/src/libp2p_bam/handler.rs
  application/comit_node/src/libp2p_bam/mod.rs
  application/comit_node/src/libp2p_bam/protocol.rs
  application/comit_node/src/logging.rs
  application/comit_node/src/network.rs
  application/comit_node/src/node_id.rs
  application/comit_node/src/settings/mod.rs
  application/comit_node/src/swap_protocols/dependencies/client_impl.rs
  application/comit_node/src/swap_protocols/dependencies/mod.rs
  application/comit_node/src/swap_protocols/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/communication_events.rs
  application/comit_node/src/swap_protocols/rfc003/alice/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/bob/spawner.rs
  vendor/bam/src/json/codec.rs
  vendor/bam/src/json/frame.rs
Labels: automagically-mergify-this, review

#924 Use Strum correctly
  application/comit_node/Cargo.toml
  application/comit_node/src/swap_protocols/metadata_store.rs
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/src/lib.rs
Labels: automagically-mergify-this, review

#931 Upgrade testcontainer-rs to 0.7
  Cargo.lock
  api_tests/regtest/docker-compose.yml
  application/btsieve/Cargo.toml
  application/comit_node/Cargo.toml
  vendor/bitcoin_rpc_test_helpers/Cargo.toml
  vendor/bitcoin_witness/Cargo.toml
  vendor/blockchain_contracts/Cargo.toml
  vendor/tc_bitcoincore_client/Cargo.toml
  vendor/tc_web3_client/Cargo.toml
Labels: automagically-mergify-this, review

#937 Renames SendTransaction to CallContract
  api_tests/lib/actor.ts
  api_tests/lib/comit.ts
  application/comit_node/src/http_api/routes/rfc003/handlers/get_action.rs
  application/comit_node/src/swap_protocols/rfc003/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/actions/ether.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/erc20.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/actions.rs
Labels: automagically-mergify-this, review

#946 Increment version after comit-i release.
  vendor/comit_i/version
Labels: automagically-mergify-this

#938 Generate ERC20/Ether HTLCs from offsets
  Cargo.lock
  vendor/blockchain_contracts/Cargo.toml
  vendor/blockchain_contracts/build.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/erc20_htlc.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/ether_htlc.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/templates/.gitignore
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/templates/deploy_header.asm
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/templates/erc20_contract.asm
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/templates/ether_contract.asm
  vendor/blockchain_contracts/src/bin/calculate_offsets/mod.rs
  vendor/blockchain_contracts/src/bin/print_offsets.rs
  vendor/blockchain_contracts/src/ethereum/mod.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/erc20.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/erc20_htlc.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/ether.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/ether_htlc.rs
  vendor/blockchain_contracts/src/ethereum/rfc003/mod.rs
  vendor/blockchain_contracts/src/lib.rs
  vendor/blockchain_contracts/src/offset_parameter.rs
  vendor/blockchain_contracts/src/rfc003/secret_hash.rs
  vendor/blockchain_contracts/src/rfc003/timestamp.rs
  vendor/blockchain_contracts/tests/htlc_harness/erc20_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/ether_harness.rs
  vendor/blockchain_contracts/tests/htlc_harness/mod.rs
  vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs
Labels: automagically-mergify-this

#944 Rewrite libp2p layer
  Cargo.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/libp2p_bam/behaviour.rs
  application/comit_node/src/libp2p_bam/handler.rs
  application/comit_node/src/libp2p_bam/mod.rs
  application/comit_node/src/libp2p_bam/protocol.rs
  application/comit_node/src/logging.rs
  vendor/bam/src/api.rs
  vendor/bam/src/client.rs
  vendor/bam/src/config.rs
  vendor/bam/src/connection.rs
  vendor/bam/src/json/codec.rs
  vendor/bam/src/json/frame.rs
  vendor/bam/src/json/request.rs
  vendor/bam/src/json/response.rs
  vendor/bam/src/lib.rs
  vendor/bam/src/shutdown_handle.rs
  vendor/bam/tests/bi_directional.rs
  vendor/bam/tests/buy_phone_request.json
  vendor/bam/tests/buy_phone_response.json
  vendor/bam/tests/buy_retro_encabulator_request.json
  vendor/bam/tests/buy_retro_encabulator_response.json
  vendor/bam/tests/common/alice_and_bob.rs
  vendor/bam/tests/common/buy.rs
  vendor/bam/tests/common/counter.rs
  vendor/bam/tests/common/macros.rs
  vendor/bam/tests/common/mod.rs
  vendor/bam/tests/common/ping.rs
  vendor/bam/tests/common/place_order.rs
  vendor/bam/tests/common/say_hello.rs
  vendor/bam/tests/common/setup.rs
  vendor/bam/tests/empty_response_id-0_ok00.json
  vendor/bam/tests/empty_response_id-10_ok00.json
  vendor/bam/tests/empty_response_se00.json
  vendor/bam/tests/malformed_request_type.json
  vendor/bam/tests/ping_with_malformed_header.json
  vendor/bam/tests/ping_with_non_mandatory_header.json
  vendor/bam/tests/place_android_phone_order_request.json
  vendor/bam/tests/place_android_phone_order_response.json
  vendor/bam/tests/place_apple_phone_order_request.json
  vendor/bam/tests/place_apple_phone_order_response.json
  vendor/bam/tests/requests.rs
  vendor/bam/tests/responses.rs
  vendor/bam/tests/say_hello_to_world_2_times_request.json
  vendor/bam/tests/say_hello_to_world_2_times_response.json
  vendor/bam/tests/say_hello_to_world_compact_header_request.json
  vendor/bam/tests/say_hello_to_world_malformed_header_request.json
  vendor/bam/tests/say_hello_to_world_request.json
  vendor/bam/tests/say_hello_to_world_response.json
  vendor/bam/tests/say_hello_to_world_response_compact_id-0.json
  vendor/bam/tests/say_hello_to_world_response_compact_id-10.json
  vendor/bam/tests/say_hello_with_unknown_mandatory_header.json
  vendor/bam/tests/unsupported_lang_header_response.json
Labels: automagically-mergify-this

#942 Initial circle ci setup
  .circleci/config.yml
Labels: blocked

#952 Migrate comit-node HTTP API to siren!
  Cargo.lock
  Cargo.toml
  Makefile.toml
  api_tests/.gitignore
  api_tests/.prettierignore
  api_tests/dry/multiple_peers.ts
  api_tests/dry/rfc003_schema.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/btc_eth/refund.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/refund.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/refund_beta.ts
  api_tests/e2e/test_creator.ts
  api_tests/lib/actor.ts
  api_tests/lib/btsieve.ts
  api_tests/lib/comit.ts
  api_tests/lib/setupChai.ts
  api_tests/package.json
  api_tests/siren.schema.json
  api_tests/swap.schema.json
  api_tests/tsconfig.json
  api_tests/webgui/webgui.ts
  api_tests/yarn.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/http_api/routes/index/handlers/get_swaps.rs
  application/comit_node/src/http_api/routes/index/mod.rs
  application/comit_node/src/http_api/routes/rfc003/action.rs
  application/comit_node/src/http_api/routes/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/swap_resource.rs
  vendor/siren/Cargo.toml
  vendor/siren/src/http_serde.rs
  vendor/siren/src/lib.rs
  vendor/siren/src/types.rs
Labels: automagically-mergify-this

#949 Update setup in README to current version
  README.md
  application/btsieve/config/default.toml
Labels: automagically-mergify-this

#965 Configure logging for btsieve in settings file and print startup messages
  Cargo.lock
  api_tests/regtest/btsieve/default.toml
  application/btsieve/Cargo.toml
  application/btsieve/config/default.toml
  application/btsieve/src/bin/btsieve.rs
  application/btsieve/src/lib.rs
  application/btsieve/src/logging.rs
  application/btsieve/src/settings/mod.rs
  application/btsieve/src/settings/serde_log.rs
Labels: automagically-mergify-this

#967 Mergify minimum 2 approvals
  .mergify.yml
Labels: automagically-mergify-this

#966 Allow config dir path to be passed via command line
  Cargo.lock
  README.md
  api_tests/harness.ts
  api_tests/lib/actor.ts
  application/comit_node/Cargo.toml
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/load_settings.rs
Labels: automagically-mergify-this

#974 Comit_node settings injections in Comit-i endpoint
  api_tests/package.json
  api_tests/regtest/david/default.toml
  api_tests/webgui/webgui.ts
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_i_routes.rs
  application/comit_node/src/settings/mod.rs
Labels: automagically-mergify-this

#979 Remove dead code
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc_params.rs
Labels: added-mid-sprint, automagically-mergify-this

#973 Btsieve Config dir path is now passed by command line
  Cargo.lock
  api_tests/btsieve/bitcoin_only/config.toml
  api_tests/btsieve/ethereum_only/config.toml
  api_tests/btsieve/no_ledger/config.toml
  api_tests/e2e/rfc003/btc_eth-erc20/config.toml
  api_tests/e2e/rfc003/btc_eth/config.toml
  api_tests/e2e/rfc003/eth-erc20_btc/config.toml
  api_tests/e2e/rfc003/eth_btc/config.toml
  api_tests/lib/btsieve.ts
  api_tests/lib/btsieve_runner.ts
  application/btsieve/Cargo.toml
  application/btsieve/src/bin/btsieve.rs
  application/btsieve/src/lib.rs
  application/btsieve/src/load_settings.rs
Labels: automagically-mergify-this

#983 Use class property in siren entities
  application/comit_node/src/http_api/routes/index/handlers/get_swaps.rs
  application/comit_node/src/http_api/swap_resource.rs
  vendor/siren/src/types.rs
Labels: automagically-mergify-this

#976 Config loading is optional
  Cargo.lock
  application/btsieve/Cargo.toml
  application/comit_node/Cargo.toml
  application/comit_node/config/default.toml
  application/comit_node/config/development.toml
  application/comit_node/src/lib.rs
  application/comit_node/src/load_settings.rs
  application/comit_node/src/logging.rs
  application/comit_node/src/seed.rs
  application/comit_node/src/settings/mod.rs
  application/comit_node/src/settings/serde_duration.rs
  application/comit_node/src/settings/serde_log.rs
Labels: automagically-mergify-this

#991 Replace TODO with ticket
  vendor/bitcoin_support/src/weight.rs
Labels: added-mid-sprint, automagically-mergify-this

#989 Remove `groomed` as the default label from dependabot
  .dependabot/config.yml
Labels: added-mid-sprint, automagically-mergify-this

#997 Update web3 to latest version and patch around receipt-bug
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/lib/ethereum.ts
  api_tests/package.json
  api_tests/yarn.lock
Labels: added-mid-sprint
