Repository comit-network/comit-rs, pull requests merged in 2019-01, with the labels that each got.

#598 Remove Accept/Decline from Alice's actions
  Cargo.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/rfc003/with_swap_types.rs
  application/comit_node/src/swap_protocols/rfc003/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/mod.rs
Labels: review

#614 Add libssl install and run `cargo make` at the end
  README.md
Labels: review

#615 Cargo make + emoji reviews
  CONTRIBUTING.md
Labels: added-mid-sprint, review

#619 Fix typo in issue template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: review

#618 Add contributor license agreement
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
Labels: review

#623 Add GET /peers to HTTP API
  api_tests/dry/rfc003/test.js
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/route_factory.rs
Labels: review

#612 Check secret length in ERC20 & ETH HTLCs
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_contract.asm
  application/comit_node/tests/htlc_harness/erc20_harness.rs
  application/comit_node/tests/htlc_harness/ether_harness.rs
  application/comit_node/tests/htlc_harness/mod.rs
  application/comit_node/tests/rfc003_bitcoin_htlc.rs
  application/comit_node/tests/rfc003_erc20_htlc.rs
  application/comit_node/tests/rfc003_ether_htlc.rs
Labels: review

#621 Adds commonly used `cargo make` tasks
  CONTRIBUTING.md
  README.md
Labels: added-mid-sprint, review

#625 Add a few checks to clippy
  Cargo.lock
  Makefile.toml
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/fake.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/ledger_query_service/fetch_transaction_stream.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/validation.rs
  application/comit_node/src/swap_protocols/rfc003/roles.rs
  application/comit_node/src/swap_protocols/rfc003/state_store.rs
  application/ledger_query_service/src/route_factory.rs
  vendor/bam/src/json/frame.rs
  vendor/bitcoin_support/src/blocks.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/bitcoin_support/src/transaction.rs
  vendor/bitcoin_support/src/weight.rs
  vendor/bitcoin_witness/Cargo.toml
  vendor/bitcoin_witness/src/primed_transaction.rs
  vendor/bitcoin_witness/tests/sign_with_rate.rs
  vendor/key_gen/Cargo.toml
  vendor/key_gen/src/main.rs
Labels: review

#613 Issue #575 split test_lib.js
  api_tests/dry/rfc003/test.js
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/e2e/rfc003/eth-erc20_btc/test.js
  api_tests/e2e/rfc003/eth_btc/test.js
  api_tests/harness.js
  api_tests/ledger_query_service/test.js
  api_tests/lib/actor.js
  api_tests/lib/bitcoin.js
  api_tests/lib/ethereum.js
  api_tests/lib/lqs.js
  api_tests/lib/util.js
  api_tests/lib/wallet.js
  api_tests/test_lib.js
Labels: review

#631 Remove unnecessary From implementation
  application/comit_node/src/swap_protocols/ledger/mod.rs
  vendor/bitcoin_support/src/pubkey.rs
Labels: review

#635 Make `SecretHash` `Copy`
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/secret.rs
Labels: review

#632 Format all JavaScript files
  Makefile.toml
  api_tests/lib/actor.js
  api_tests/lib/ethereum.js
Labels: review

#630 Add inbound connections to client pool
  api_tests/dry/rfc003/test.js
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/fake.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/comit_server.rs
Labels: review

#645 Only mergify a pr if correct label is set
  .github/PULL_REQUEST_TEMPLATE.md
  .mergify.yml
Labels: automagically-mergify-this, review

#648 Replacement PR for #616
  Cargo.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/bin/comit_node.rs
Labels: automagically-mergify-this, review

#617 Update testcontainers to use parity 2.1.3 across the board
  Cargo.lock
  Cargo.toml
  Makefile.toml
  application/comit_node/Cargo.toml
  application/ledger_query_service/Cargo.toml
  vendor/bitcoin_rpc_test_helpers/Cargo.toml
  vendor/bitcoin_witness/Cargo.toml
  vendor/tc_bitcoincore_client/Cargo.toml
  vendor/tc_web3_client/Cargo.toml
Labels: automagically-mergify-this, review

#677 Decouple config from connection
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_server.rs
  vendor/bam/src/api.rs
  vendor/bam/src/connection.rs
  vendor/bam/src/json/frame.rs
  vendor/bam/tests/bi_directional.rs
  vendor/bam/tests/common/alice_and_bob.rs
Labels: automagically-mergify-this

#674 Do not proceed if invalid e2e folder
  Makefile.toml
Labels: automagically-mergify-this, review

#683 Remove IsEmpty trait
  application/ledger_query_service/src/bitcoin/block_processor.rs
  application/ledger_query_service/src/bitcoin/queries.rs
  application/ledger_query_service/src/ethereum/queries.rs
  application/ledger_query_service/src/lib.rs
  application/ledger_query_service/src/route_factory.rs
  application/ledger_query_service/src/routes.rs
Labels: automagically-mergify-this

#675 Update README + Fix mergify corner case
  .mergify.yml
  README.md
  application/comit_node/build.rs
Labels: automagically-mergify-this, review

#682 Bitcoin LQS cleanup
  api_tests/ledger_query_service/test.js
  application/ledger_query_service/src/bin/ledger_query_service.rs
  application/ledger_query_service/src/bitcoin/block_processor.rs
  application/ledger_query_service/src/bitcoin/mod.rs
  application/ledger_query_service/src/bitcoin/queries.rs
  application/ledger_query_service/src/ethereum/block_processor.rs
  application/ledger_query_service/src/ethereum/queries.rs
  application/ledger_query_service/src/lib.rs
Labels: automagically-mergify-this, review

#684 Verify erc20 funding using LQS
  api_tests/ledger_query_service/test.js
  application/ledger_query_service/src/bin/ledger_query_service.rs
  application/ledger_query_service/src/ethereum/block_processor.rs
  application/ledger_query_service/src/ethereum/mod.rs
  application/ledger_query_service/src/ethereum/queries.rs
  application/ledger_query_service/src/ethereum/queries/block_query.rs
  application/ledger_query_service/src/ethereum/queries/event_query.rs
  application/ledger_query_service/src/ethereum/queries/mod.rs
  application/ledger_query_service/src/ethereum/queries/transaction_query.rs
Labels: automagically-mergify-this, review

#696 563 use new lqs features
  application/comit_node/src/ledger_query_service/client.rs
  application/comit_node/src/ledger_query_service/ethereum.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs
  application/ledger_query_service/src/ethereum/queries/event_query.rs
Labels: automagically-mergify-this, review

#720 Remove keystore module
  application/comit_node/src/key_store/fake_key_store.rs
  application/comit_node/src/key_store/mod.rs
Labels: automagically-mergify-this, review

#719 Remove TODO
  application/comit_node/src/swap_protocols/rfc003/bitcoin/actions.rs
Labels: automagically-mergify-this, review

#718 Settings no longer contain private keys
  application/comit_node/src/bin/comit_node.rs
Labels: automagically-mergify-this, review

#721 Remove noisy log messages
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/erc20_htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/ether_htlc.rs
Labels: automagically-mergify-this, review

#695 Refactor bam-crate to use dedicated Header struct
  Cargo.lock
  application/comit_node/Cargo.toml
  application/comit_node/src/bam_api/header.rs
  application/comit_node/src/bam_api/mod.rs
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/bam_ext.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/client.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/rfc003/with_swap_types.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/swap_protocols/asset.rs
  application/comit_node/src/swap_protocols/ledger/bitcoin.rs
  application/comit_node/src/swap_protocols/ledger/ethereum.rs
  application/comit_node/src/swap_protocols/ledger/mod.rs
  application/comit_node/src/swap_protocols/metadata_store.rs
  application/comit_node/src/swap_protocols/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20_btc.rs
  application/comit_node/src/swap_protocols/rfc003/alice/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/erc20_btc.rs
  application/comit_node/src/swap_protocols/rfc003/bob/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/create_ledger_events.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/erc20_htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/validation.rs
  application/comit_node/src/swap_protocols/rfc003/events/lqs.rs
  application/comit_node/tests/htlc_harness/erc20_harness.rs
  vendor/bam/src/api.rs
  vendor/bam/src/client.rs
  vendor/bam/src/json/frame.rs
  vendor/bam/src/json/header.rs
  vendor/bam/src/json/mod.rs
  vendor/bam/src/json/request.rs
  vendor/bam/src/json/response.rs
  vendor/bam/src/lib.rs
  vendor/bam/tests/bi_directional.rs
  vendor/bam/tests/common/alice_and_bob.rs
  vendor/bam/tests/common/buy.rs
  vendor/bam/tests/common/counter.rs
  vendor/bam/tests/common/ping.rs
  vendor/bam/tests/common/place_order.rs
  vendor/bam/tests/common/say_hello.rs
  vendor/bam/tests/common/setup.rs
  vendor/bam/tests/responses.rs
  vendor/ethereum_support/src/erc20_quantity.rs
  vendor/ethereum_support/src/erc20_token.rs
  vendor/ethereum_support/src/lib.rs
Labels: automagically-mergify-this, review

#725 All swap parameters set by Alice + use absolute timelocks in HTLCs
  Cargo.lock
  api_tests/dry/rfc003/test.js
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/e2e/rfc003/eth-erc20_btc/test.js
  api_tests/e2e/rfc003/eth_btc/test.js
  application/comit_node/Cargo.toml
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/rfc003.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/swap_protocols/rfc003/alice/communication_events.rs
  application/comit_node/src/swap_protocols/rfc003/alice/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/alice/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/actions.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/validation.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_eth.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/bob/swap_request.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_deploy_header.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_deploy_header.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/erc20_htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/ether_htlc.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/src/swap_protocols/rfc003/events/mod.rs
  application/comit_node/src/swap_protocols/rfc003/mod.rs
  application/comit_node/src/swap_protocols/rfc003/role.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine_test.rs
  application/comit_node/src/swap_protocols/rfc003/state_store.rs
  application/comit_node/src/swap_protocols/rfc003/timestamp.rs
  application/comit_node/tests/htlc_harness/erc20_harness.rs
  application/comit_node/tests/htlc_harness/ether_harness.rs
  application/comit_node/tests/htlc_harness/mod.rs
  application/comit_node/tests/rfc003_bitcoin_htlc.rs
  application/comit_node/tests/rfc003_erc20_htlc.rs
  application/comit_node/tests/rfc003_ether_htlc.rs
  application/ledger_query_service/src/ethereum/queries/event_query.rs
  vendor/bitcoin_witness/src/p2wpkh.rs
  vendor/bitcoin_witness/src/primed_transaction.rs
  vendor/bitcoin_witness/src/witness.rs
  vendor/bitcoin_witness/tests/p2wpkh.rs
  vendor/bitcoin_witness/tests/sign_with_rate.rs
Labels: automagically-mergify-this, review
