Repository comit-network/comit-rs, pull requests merged in 2019-02, with the labels that each got.

#688 Introduce ConnectionPool to replace BamClientPool
  application/comit_node/src/bam_api/rfc003/swap.rs
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/comit_client/bam.rs
  application/comit_node/src/comit_client/client.rs
  application/comit_node/src/comit_client/fake.rs
  application/comit_node/src/comit_client/mod.rs
  application/comit_node/src/comit_server.rs
  application/comit_node/src/connection_pool.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/rfc003/swap.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/lib.rs
  application/comit_node/src/node_id.rs
  application/comit_node/src/swap_protocols/dependencies.rs
  application/comit_node/src/swap_protocols/dependencies/client_impl.rs
  application/comit_node/src/swap_protocols/dependencies/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/communication_events.rs
  application/comit_node/src/swap_protocols/rfc003/alice/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/bob/spawner.rs
  application/comit_node/src/swap_protocols/rfc003/error.rs
Labels: review

#733 Add log_level option to settings
  application/comit_node/config/development.toml
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/logging.rs
  application/comit_node/src/settings/mod.rs
  application/comit_node/src/settings/serde/log_level.rs
  application/comit_node/src/settings/serde/mod.rs
Labels: automagically-mergify-this, review

#732 Noise Handshake Future
  .idea/swap.iml
  Cargo.lock
  Cargo.toml
  application/comit_node/Cargo.toml
  vendor/noise_handshake/Cargo.toml
  vendor/noise_handshake/src/handshake.rs
  vendor/noise_handshake/src/lib.rs
Labels: automagically-mergify-this, review

#743 Fix RLP encoding error
  application/comit_node/tests/ethereum_wallet/transaction.rs
Labels: added-mid-sprint, review

#748 Fix LQS Client test
  application/comit_node/src/ledger_query_service/client.rs
Labels: automagically-mergify-this, review

#737 Split up dry tests
  Makefile.toml
  api_tests/dry/config.toml
  api_tests/dry/multiple_peers.js
  api_tests/dry/rfc003/test.js
  api_tests/dry/rfc003_swap_reject.js
  api_tests/dry/stateless.js
  api_tests/harness.js
Labels: automagically-mergify-this, review

#755 Run JS check format before commit
  .githooks/pre-commit
  Makefile.toml
Labels: automagically-mergify-this, review

#750 Resolve TODO
  vendor/bam/src/json/frame.rs
Labels: automagically-mergify-this

#761 Don't use --all-targets as it doesn't run doc tests
  Makefile.toml
Labels: automagically-mergify-this

#759 Remove TODO in bitcoin_rpc_test_helpers
  vendor/bitcoin_rpc_test_helpers/src/lib.rs
Labels: automagically-mergify-this

#780 Use draft PR instead of WIP title
  .mergify.yml
Labels: review

#756 A significant Refactor of Ledger Query Service Client
  .idea/swap.iml
  application/comit_node/src/bin/comit_node.rs
  application/comit_node/src/btsieve/bitcoin.rs
  application/comit_node/src/btsieve/cache.rs
  application/comit_node/src/btsieve/client.rs
  application/comit_node/src/btsieve/ethereum.rs
  application/comit_node/src/btsieve/fake_btsieve.rs
  application/comit_node/src/btsieve/fetch_transaction_stream.rs
  application/comit_node/src/btsieve/first_match.rs
  application/comit_node/src/btsieve/mod.rs
  application/comit_node/src/btsieve/poll_until_item.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swap.rs
  application/comit_node/src/swap_protocols/asset.rs
  application/comit_node/src/swap_protocols/dependencies/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/extract_secret.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc_events.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc_params.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/queries.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/validation.rs
  application/comit_node/src/swap_protocols/rfc003/create_ledger_events.rs
  application/comit_node/src/swap_protocols/rfc003/error.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/extract_secret.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/htlc_events.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/queries.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/validation.rs
  application/comit_node/src/swap_protocols/rfc003/events/btsieve.rs
  application/comit_node/src/swap_protocols/rfc003/events/ledger_event_futures.rs
  application/comit_node/src/swap_protocols/rfc003/events/mod.rs
  application/comit_node/src/swap_protocols/rfc003/find_htlc_location.rs
  application/comit_node/src/swap_protocols/rfc003/ledger.rs
  application/comit_node/src/swap_protocols/rfc003/ledger_state.rs
  application/comit_node/src/swap_protocols/rfc003/mod.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine_test.rs
  application/comit_node/src/swap_protocols/rfc003/state_store.rs
Labels: review

#782 Minor name changes in get swap/list swaps http api responses
  api_tests/dry/multiple_peers.js
  api_tests/dry/rfc003_swap_reject.js
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/e2e/rfc003/eth-erc20_btc/test.js
  api_tests/e2e/rfc003/eth_btc/test.js
  application/comit_node/src/http_api/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
Labels: review

#786 Use more-concise prettier configuration
  Makefile.toml
  api_tests/yarn.lock
Labels: automagically-mergify-this, review

#785 Take direct control of serialization in HTTP API
  Cargo.lock
  application/comit_node/src/bam_api/mod.rs
  application/comit_node/src/http_api/asset.rs
  application/comit_node/src/http_api/impl_serialize_http.rs
  application/comit_node/src/http_api/ledger.rs
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
  application/comit_node/src/http_api/rfc003/handlers/post_swap.rs
  application/comit_node/src/http_api/rfc003/mod.rs
  application/comit_node/src/swap_protocols/asset.rs
  application/comit_node/src/swap_protocols/ledger/mod.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/erc20_btc.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/btc_erc20.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/htlc_events.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  rustfmt.toml
  vendor/ethereum_support/src/erc20_quantity.rs
  vendor/ethereum_support/src/erc20_token.rs
Labels: automagically-mergify-this, review

#784 Extract Secret and Asset from contract logs for Ethereum HTLCs
  Cargo.lock
  api_tests/btsieve/config.toml
  api_tests/btsieve/test.js
  api_tests/package.json
  api_tests/yarn.lock
  application/btsieve/Cargo.toml
  application/btsieve/src/bin/btsieve.rs
  application/btsieve/src/bitcoin/queries/block.rs
  application/btsieve/src/bitcoin/queries/mod.rs
  application/btsieve/src/bitcoin/queries/transaction.rs
  application/btsieve/src/ethereum/queries/block.rs
  application/btsieve/src/ethereum/queries/event.rs
  application/btsieve/src/ethereum/queries/mod.rs
  application/btsieve/src/ethereum/queries/transaction.rs
  application/btsieve/src/lib.rs
  application/btsieve/src/route_factory.rs
  application/btsieve/src/routes.rs
  application/comit_node/src/btsieve/client.rs
  application/comit_node/src/btsieve/ethereum.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/erc20_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/contract_templates/ether_contract.asm
  application/comit_node/src/swap_protocols/rfc003/ethereum/extract_secret.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/htlc_events.rs
  application/comit_node/src/swap_protocols/rfc003/ethereum/mod.rs
  application/comit_node/tests/rfc003_erc20_htlc.rs
  application/comit_node/tests/rfc003_ether_htlc.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/ethereum_support/src/lib.rs
Labels: automagically-mergify-this, review

#788 Upgrade bitcoinjs-lib to make use of built-in regtest definition
  api_tests/lib/bitcoin.js
  api_tests/yarn.lock
Labels: automagically-mergify-this, review

#789 Fix warning in build process
  Makefile.toml
Labels: added-mid-sprint, automagically-mergify-this, review

#783 Add actions to GET swaps
  api_tests/dry/multiple_peers.js
  api_tests/dry/rfc003_swap_reject.js
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/e2e/rfc003/eth-erc20_btc/test.js
  api_tests/e2e/rfc003/eth_btc/test.js
  application/comit_node/src/http_api/mod.rs
  application/comit_node/src/http_api/problem.rs
  application/comit_node/src/http_api/rfc003/action.rs
  application/comit_node/src/http_api/rfc003/handlers/get_action.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
  application/comit_node/src/http_api/rfc003/handlers/mod.rs
  application/comit_node/src/http_api/rfc003/handlers/post_action.rs
  application/comit_node/src/http_api/rfc003/mod.rs
  application/comit_node/src/http_api/rfc003/routes.rs
  application/comit_node/src/http_api/route_factory.rs
  application/comit_node/src/swap_protocols/rfc003/alice/actions/mod.rs
  application/comit_node/src/swap_protocols/rfc003/bob/actions/mod.rs
Labels: automagically-mergify-this, review

#792 Delete ItemCache
  application/comit_node/src/item_cache.rs
  application/comit_node/src/lib.rs
Labels: review

#787 Verify Bitcoin redeem transaction using transaction ID
  api_tests/e2e/rfc003/btc_eth-erc20/test.js
  api_tests/e2e/rfc003/btc_eth/test.js
  api_tests/e2e/rfc003/eth-erc20_btc/test.js
  api_tests/e2e/rfc003/eth_btc/test.js
  api_tests/harness.js
  api_tests/lib/bitcoin.js
  api_tests/lib/ethereum.js
  api_tests/lib/wallet.js
  api_tests/package.json
  api_tests/yarn.lock
Labels: automagically-mergify-this, review

#790 Enable clippy::dbg_macro lint
  Cargo.lock
  Makefile.toml
  application/btsieve/Cargo.toml
  application/btsieve/src/bitcoin/block_processor.rs
  application/btsieve/src/ethereum/block_processor.rs
  application/comit_node/Cargo.toml
  application/comit_node/src/comit_server.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swap.rs
  application/comit_node/src/http_api/rfc003/handlers/get_swaps.rs
  application/comit_node/src/http_api/rfc003/handlers/post_swap.rs
  application/comit_node/src/swap_protocols/dependencies/client_impl.rs
  application/comit_node/src/swap_protocols/rfc003/bitcoin/htlc.rs
  application/comit_node/src/swap_protocols/rfc003/state_machine.rs
  rust-toolchain
  vendor/bitcoin_support/src/lib.rs
  vendor/noise_handshake/Cargo.toml
  vendor/noise_handshake/src/handshake.rs
  vendor/noise_handshake/src/lib.rs
  vendor/secp256k1_support/src/keypair.rs
Labels: automagically-mergify-this, review

#794 Deactivate bitcoind `-acceptnonstdtxn` in tests
  Cargo.lock
  api_tests/regtest/docker-compose.yml
  application/btsieve/Cargo.toml
  application/comit_node/Cargo.toml
  vendor/bitcoin_rpc_test_helpers/Cargo.toml
  vendor/bitcoin_witness/Cargo.toml
  vendor/tc_bitcoincore_client/Cargo.toml
  vendor/tc_web3_client/Cargo.toml
Labels: automagically-mergify-this, review

#798 TODO already tracked with #376
  application/comit_node/src/swap_protocols/ledger/bitcoin.rs
Labels: automagically-mergify-this, review
