Repository comit-network/comit-rs, pull requests merged in 2019-07, with the labels that each got.

#1059 Add automagically-mergify-this label by default
  .dependabot/config.yml
Labels: automagically-mergify-this

#1055 Check format based on file suffix
  .githooks/pre-commit
Labels: automagically-mergify-this

#1053 Print offsets for Bitcoin Basic HTLC script
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/compile_contract.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/templates/bitcoin/config.json
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/templates/bitcoin/contract.script
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/compile_contract.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/contract.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/metadata.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/offset.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/placeholder_config.rs
  vendor/blockchain_contracts/src/bin/print_offsets.rs
Labels: automagically-mergify-this

#1032 Calculate fee for Bitcoin tx correctly
  api_tests/lib/actor.ts
  application/comit_node/src/http_api/action.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_support/src/weight.rs
  vendor/bitcoin_witness/src/primed_transaction.rs
  vendor/bitcoin_witness/tests/sign_with_rate.rs
Labels: automagically-mergify-this

#1065 Minor simplifications for the offset calculations of the bitcoin HTLC
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/compile_contract.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/bitcoin/rfc003/mod.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/ethereum/rfc003/contract.rs
  vendor/blockchain_contracts/src/bin/calculate_offsets/mod.rs
Labels: automagically-mergify-this

#1069 Simplify root Cargo.toml through catch-all * syntax
  Cargo.toml
Labels: automagically-mergify-this

#1052 Add unit tests for HTTP API primitive types
  application/comit_node/src/http_api/mod.rs
Labels: automagically-mergify-this

#1080 Remove hard coded paths
  btsieve/src/load_settings.rs
  comit_node/src/load_settings.rs
Labels: automagically-mergify-this

#1083 Introduce Cargo.toml formatting to avoid manual sorting
  .githooks/pre-commit
  Cargo.toml
  Makefile.toml
  vendor/bitcoin_rpc_test_helpers/Cargo.toml
  vendor/bitcoin_support/Cargo.toml
  vendor/bitcoin_witness/Cargo.toml
  vendor/blockchain_contracts/Cargo.toml
  vendor/comit_i/Cargo.toml
  vendor/ethereum_support/Cargo.toml
  vendor/siren/Cargo.toml
  vendor/tc_bitcoincore_client/Cargo.toml
Labels: automagically-mergify-this

#1084 Update stale config file instructions
  README.md
Labels: automagically-mergify-this

#1087 Unify the way we specify dependencies in Cargo.toml
  Cargo.toml
  btsieve/Cargo.toml
  comit_node/Cargo.toml
  vendor/key_gen/Cargo.toml
Labels: automagically-mergify-this

#1093 Configure dependabot to update e2e tests dependencies
  .dependabot/config.yml
Labels: automagically-mergify-this

#1100 Add TS Linter and allow e2e tests to be run with yarn
  .githooks/pre-commit
  Cargo.lock
  Makefile.toml
  README.md
  api_tests/.gitignore
  api_tests/btsieve/bitcoin_only/test.ts
  api_tests/btsieve/ethereum_only/test.ts
  api_tests/btsieve/no_ledger/test.ts
  api_tests/dry/multiple_peers.ts
  api_tests/dry/peers_using_ip.ts
  api_tests/dry/rfc003_schema.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/btc_eth/inverted_refund.ts
  api_tests/e2e/rfc003/btc_eth/refund.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/refund.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/refund_beta.ts
  api_tests/harness.ts
  api_tests/lib/actor.ts
  api_tests/lib/bitcoin.ts
  api_tests/lib/btsieve.ts
  api_tests/lib/btsieve_runner.ts
  api_tests/lib/comit.ts
  api_tests/lib/ethereum.ts
  api_tests/lib/ledger_runner.ts
  api_tests/lib/satoshi_bitcoin.d.ts
  api_tests/lib/setupChai.ts
  api_tests/lib/test_creator.ts
  api_tests/lib/wallet.ts
  api_tests/package.json
  api_tests/tslint.json
  api_tests/webgui/webgui.ts
  api_tests/yarn.lock
Labels: automagically-mergify-this

#1101 Return 400 when fee is too high
  api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts
  api_tests/lib/actor.ts
  api_tests/lib/test_creator.ts
  comit_node/src/http_api/action.rs
  vendor/bitcoin_witness/src/primed_transaction.rs
Labels: automagically-mergify-this

#1103 Enforce camelCase for var names, snake_case for filenames
  api_tests/btsieve/bitcoin_only/test.ts
  api_tests/btsieve/ethereum_only/test.ts
  api_tests/btsieve/no_ledger/test.ts
  api_tests/dry/multiple_peers.ts
  api_tests/dry/peers_using_ip.ts
  api_tests/dry/rfc003_schema.ts
  api_tests/dry/rfc003_swap_reject.ts
  api_tests/dry/sanity.ts
  api_tests/e2e/rfc003/btc_eth-erc20/happy.ts
  api_tests/e2e/rfc003/btc_eth-erc20/refund_beta.ts
  api_tests/e2e/rfc003/btc_eth/happy.ts
  api_tests/e2e/rfc003/btc_eth/inverted_refund.ts
  api_tests/e2e/rfc003/btc_eth/refund.ts
  api_tests/e2e/rfc003/eth-erc20_btc/happy.ts
  api_tests/e2e/rfc003/eth-erc20_btc/refund.ts
  api_tests/e2e/rfc003/eth_btc/bitcoin_high_fee.ts
  api_tests/e2e/rfc003/eth_btc/happy.ts
  api_tests/e2e/rfc003/eth_btc/refund_beta.ts
  api_tests/harness.ts
  api_tests/lib/actor.ts
  api_tests/lib/bitcoin.ts
  api_tests/lib/btsieve.ts
  api_tests/lib/btsieve_runner.ts
  api_tests/lib/ethereum.ts
  api_tests/lib/ledger_runner.ts
  api_tests/lib/setup_chai.ts
  api_tests/lib/test_creator.ts
  api_tests/lib/util.ts
  api_tests/lib/wallet.ts
  api_tests/tslint.json
Labels: automagically-mergify-this, 🥰 feels-good

#1110 Remove `signature` module from `secp256k1_support`
  vendor/bitcoin_witness/src/primed_transaction.rs
  vendor/blockchain_contracts/tests/ethereum_wallet/wallet.rs
  vendor/secp256k1_support/src/lib.rs
  vendor/secp256k1_support/src/signature.rs
Labels: added-mid-sprint, automagically-mergify-this

#1111 Make `hex` a dev-dependency and use functions provided by `secp256k1`
  vendor/bitcoin_support/src/pubkey.rs
  vendor/secp256k1_support/Cargo.toml
  vendor/secp256k1_support/src/keypair.rs
  vendor/secp256k1_support/src/public_key.rs
Labels: added-mid-sprint, automagically-mergify-this

#1107 Enable the 'overflow_delimited_expr' rustfmt option
  comit_node/src/http_api/mod.rs
  comit_node/src/swap_protocols/rfc003/alice/spawner.rs
  comit_node/src/swap_protocols/rfc003/bob/spawner.rs
  comit_node/src/swap_protocols/rfc003/secret.rs
  comit_node/src/swap_protocols/rfc003/state_machine.rs
  rustfmt.toml
  vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
Labels: automagically-mergify-this

#1112 Use correct bitcoin network names
  vendor/bitcoin_support/src/network.rs
Labels: automagically-mergify-this

#1120 Remove grpc dependency
  api_tests/package.json
  api_tests/yarn.lock
Labels: automagically-mergify-this, 🥰 feels-good

#1126 Fix btsieve-client network bug
  comit_node/src/btsieve/client.rs
  comit_node/src/main.rs
  comit_node/src/settings/mod.rs
  vendor/bitcoin_support/src/network.rs
  vendor/ethereum_support/src/network.rs
Labels: automagically-mergify-this, 🐛 bug

#1127 Second fix of network serialization for serde
  vendor/bitcoin_support/src/network.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/key_gen/src/main.rs
Labels: automagically-mergify-this, 🐛 bug

#1128 Revert "Second fix of network serialization for serde"
  vendor/bitcoin_support/src/network.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/key_gen/src/main.rs
Labels: automagically-mergify-this

#1136 Do the safety dance!
  README.md
  btsieve/src/lib.rs
  btsieve/src/main.rs
  comit_node/src/lib.rs
  comit_node/src/main.rs
  vendor/bam/src/lib.rs
  vendor/bitcoin_rpc_test_helpers/src/lib.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/bitcoin_witness/src/lib.rs
  vendor/blockchain_contracts/src/lib.rs
  vendor/blockchain_contracts/tests/rfc003_bitcoin_htlc.rs
  vendor/blockchain_contracts/tests/rfc003_erc20_htlc.rs
  vendor/blockchain_contracts/tests/rfc003_ether_htlc.rs
  vendor/comit_i/src/lib.rs
  vendor/ethereum_support/src/lib.rs
  vendor/key_gen/src/main.rs
  vendor/secp256k1_support/src/lib.rs
  vendor/siren/src/http_serde.rs
  vendor/siren/src/lib.rs
  vendor/tc_bitcoincore_client/src/lib.rs
  vendor/tc_web3_client/src/lib.rs
Labels: added-mid-sprint, automagically-mergify-this

#1125 Remove executable permissions
  api_tests/harness.ts
  btsieve/src/main.rs
  comit_node/src/lib.rs
  comit_node/src/main.rs
  comit_node/src/swap_protocols/rfc003/state_machine.rs
  vendor/bitcoin_support/src/lib.rs
  vendor/key_gen/src/main.rs
Labels: added-mid-sprint, automagically-mergify-this

#1150 FIX CIRCLE-CI: Run `restore_caches` and `setup_rust` steps before `setup_system`
  .circleci/config.yml
Labels: automagically-mergify-this

#1148 Remove some unused packages and move TS + prettier to devDependencies
  api_tests/package.json
Labels: automagically-mergify-this

#1151 Remove side-effect from `load_settings` and test thoroughly
  Cargo.lock
  cnd/Cargo.toml
  cnd/src/cli.rs
  cnd/src/lib.rs
  cnd/src/load_settings.rs
  cnd/src/logging.rs
  cnd/src/main.rs
  cnd/src/seed.rs
  cnd/src/settings/mod.rs
  cnd/src/std_ext.rs
  cnd/tests/settings.rs
Labels: automagically-mergify-this

#1152 Move `tempfile` to dev-dependencies
  cnd/Cargo.toml
Labels: automagically-mergify-this

#1149 Remove issue and PR templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: automagically-mergify-this, 🥰 feels-good

#1156 Update yarn lock
  api_tests/yarn.lock
Labels: added-mid-sprint

#1153 Split `Settings` into `Settings` and `ConfigFile`
  Cargo.lock
  cnd/Cargo.toml
  cnd/config/cnd.toml
  cnd/src/comit_i_routes.rs
  cnd/src/config/config_file.rs
  cnd/src/config/mod.rs
  cnd/src/config/serde_duration.rs
  cnd/src/config/settings.rs
  cnd/src/lib.rs
  cnd/src/logging.rs
  cnd/src/main.rs
  cnd/src/settings/serde_log.rs
  cnd/tests/config.rs
Labels: automagically-mergify-this

#1157 Upgrade rustfmt toolchain to nightly-2019-07-31
  .circleci/config.yml
  Makefile.toml
  README.md
  btsieve/src/bitcoin/queries/block.rs
  btsieve/src/settings/mod.rs
  cnd/src/btsieve/client.rs
  cnd/src/http_api/action.rs
  cnd/src/http_api/ledger.rs
  cnd/src/swap_protocols/dependencies/mod.rs
  cnd/src/swap_protocols/rfc003/actions/mod.rs
  rustfmt.toml
  vendor/bam/src/json/header.rs
  vendor/bitcoin_support/src/blocks.rs
  vendor/bitcoin_support/src/pubkey.rs
  vendor/bitcoin_support/src/transaction.rs
  vendor/bitcoin_witness/src/p2wpkh.rs
  vendor/ethereum_support/src/u256_ext.rs
Labels: automagically-mergify-this
